{
 "title": "Hipstershop Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "At Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of Request",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "delta(opencensus_io_http_server_request_count[1m])",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(opencensus_io_http_server_response_count_by_status_code{http_status=\"500\"}) / sum(opencensus_io_http_server_response_count_by_status_code) * 100"
    }
   ]
  },
  {
   "title": "Avg Response Size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_response_bytes_sum[1m])/rate(opencensus_io_http_server_response_bytes_count[1m])",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "95% Percentile Latency",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_server_latency_bucket[5m])) by (le))",
     "legendFormat": "Today "
    }
   ]
  },
  {
   "title": "Hipster Shop Overall Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(opencensus_io_http_server_latency_bucket[5m])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_server_latency_bucket[5m])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(opencensus_io_http_server_latency_bucket[5m])) by (le))",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "95th percentile Latency By gRPC Method",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=~\".*Convert\"}[5m])) by (le))",
     "legendFormat": "Convert"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=~\".*GetAds\"}[5m])) by (le))",
     "legendFormat": "GetAds"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=~\".*AddItem\"}[5m])) by (le))",
     "legendFormat": "GetAds"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=~\".*PlaceOrder\"}[5m])) by (le))",
     "legendFormat": "PlaceOrder"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=~\".*GetProduct\"}[5m])) by (le))",
     "legendFormat": "GetProducts"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=~\".*ListProducts\"}[5m])) by (le))",
     "legendFormat": "ListProducts"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{grpc_client_method=~\".*GetCart\"}[5m])) by (le))",
     "legendFormat": "GetCart"
    }
   ]
  },
  {
   "title": "Average Latency By GRPC Method",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_io_client_roundtrip_latency_sum[5m])/rate(grpc_io_client_roundtrip_latency_count[5m])",
     "legendFormat": "{{grpc_client_method}}"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(opencensus_io_http_server_latency_bucket[10m])) by (le)"
    }
   ]
  },
  {
   "title": "Number of Response by Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "# of request / sec" }
   ],
   "targets": [
    {
     "expr": "delta(opencensus_io_http_server_response_count_by_status_code[1m])",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "Request and Response BW",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Request bytes/sec" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_request_bytes_sum[5m])",
     "legendFormat": "Request-{{job}}"
    },
    {
     "expr": "rate(opencensus_io_http_server_response_bytes_sum[5m])",
     "legendFormat": "Response-{{job}}"
    }
   ]
  },
  { "title": "Response Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } }
 ]
}